# Generated by Django 3.0.6 on 2020-05-06 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='First name')),
                ('surename', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/teams/%Y/%m/%d/players/', verbose_name='Player photo')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('league', models.CharField(max_length=200, null=True, verbose_name='League')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Slug')),
                ('standings_order', models.IntegerField(choices=[(0, 'Points, Wins, Lost'), (1, 'Points, Score')], default=0, verbose_name='Standings order')),
                ('win_points', models.IntegerField(default=0, null=True, verbose_name='Points for win')),
                ('lost_points', models.IntegerField(default=0, null=True, verbose_name='Points for loss')),
                ('draw_points', models.IntegerField(default=0, null=True, verbose_name='Points for draw')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='league.Player', verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=1, verbose_name='Week')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('result', models.IntegerField(choices=[(0, '1/2-1/2'), (1, '1-0'), (2, '0-1')], default=0, verbose_name='Standings order')),
                ('black', smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='player', on_delete=django.db.models.deletion.CASCADE, related_name='black', to='league.Player', verbose_name='Black')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season', verbose_name='Season')),
                ('white', smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='player', on_delete=django.db.models.deletion.CASCADE, related_name='white', to='league.Player', verbose_name='White')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='PlayerCustomFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field_order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=1, null=True, verbose_name='Position')),
                ('matches', models.IntegerField(blank=True, default=0, null=True, verbose_name='Matches')),
                ('win', models.IntegerField(default=0, null=True, verbose_name='Won')),
                ('lost', models.IntegerField(default=0, null=True, verbose_name='Lost')),
                ('draws', models.IntegerField(default=0, null=True, verbose_name='Draw')),
                ('points', models.IntegerField(default=0, null=True, verbose_name='Points')),
                ('player', smart_selects.db_fields.ChainedForeignKey(chained_field='season', chained_model_field='teams', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='league.Player', verbose_name='Team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season', verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ('-points', '-win', 'lost'),
                'unique_together': {('season', 'player')},
            },
        ),
    ]
