# Generated by Django 3.0.6 on 2020-05-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200506_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='result',
            field=models.IntegerField(choices=[(0, '1/2-1/2'), (1, '1-0'), (2, '0-1')], default=0, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='season',
            name='standings_order',
            field=models.IntegerField(choices=[(0, 'Points, Wins, Lost'), (1, 'Points, Score')], default=0, verbose_name='Standings order'),
        ),
    ]
