# Generated by Django 3.0.6 on 2020-05-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20200506_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player', verbose_name='Black'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to='league.Player', verbose_name='White'),
        ),
    ]
