# Generated by Django 3.0.6 on 2020-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20200506_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pgn',
            field=models.TextField(null=True),
        ),
    ]
