# Generated by Django 3.0.6 on 2020-05-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_schedule_pgn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lichess',
            field=models.CharField(max_length=200, null=True, verbose_name='Lichess ID'),
        ),
    ]
