# Generated by Django 3.0.6 on 2020-05-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_lichess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pgn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Week'),
        ),
    ]
