# Generated by Django 3.0.6 on 2020-06-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_auto_20200614_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='standings',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League', verbose_name='League'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('leagues', models.ManyToManyField(blank=True, related_name='leagues', to='league.League', verbose_name='Leagues')),
                ('players', models.ManyToManyField(blank=True, related_name='season_players', to='league.Player', verbose_name='Season Players')),
            ],
        ),
    ]
