# Generated by Django 3.0.6 on 2020-06-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_auto_20200614_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league',
        ),
        migrations.RemoveField(
            model_name='season',
            name='leagues',
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='league.Player', verbose_name='Seasons'),
        ),
    ]
