# Generated by Django 3.0.6 on 2020-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_auto_20200614_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
