# Generated by Django 3.0.6 on 2020-06-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_league_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ecf',
            field=models.CharField(max_length=4, null=True, verbose_name='ECF Grading Ref'),
        ),
        migrations.AlterField(
            model_name='league',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
