# Generated by Django 3.0.6 on 2020-06-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_auto_20200616_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
    ]
