# Generated by Django 3.0.6 on 2020-06-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_season_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='form',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
