# Generated by Django 3.0.6 on 2020-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_standings_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('fen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='ecf',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='ECF Grading Ref'),
        ),
        migrations.AlterField(
            model_name='player',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ECF Grade'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lichess',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lichess ID'),
        ),
    ]
