# Generated by Django 3.0.6 on 2020-06-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0019_auto_20200620_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puzzle',
        ),
    ]
