# Generated by Django 3.1.3 on 2020-12-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_delete_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='round',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='result',
            field=models.IntegerField(choices=[(0, '1/2-1/2'), (1, '1-0'), (2, '0-1'), (3, '-')], default=3, verbose_name='result'),
        ),
    ]
