# Generated by Django 3.1.3 on 2020-12-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0021_auto_20201221_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='round',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Round'),
        ),
    ]
