# Generated by Django 3.1.3 on 2020-12-25 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0022_auto_20201221_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lichess',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lichess ID'),
        ),
    ]
