# Generated by Django 3.1.3 on 2020-12-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_auto_20201225_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='surename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='round',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round'),
        ),
    ]
