# Generated by Django 3.1.3 on 2021-01-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_auto_20210128_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.IntegerField(choices=[(0, 'League'), (1, 'Swiss'), (2, 'Round Robin')], default=0),
        ),
    ]
