# Generated by Django 3.1.3 on 2021-02-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_auto_20210128_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ('-points', '-win', 'lost', '-rating', 'player__surename'), 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='draw_points',
            field=models.IntegerField(choices=[(0, '0'), (1, '0.5'), (2, '1'), (3, '2'), (4, '3')], default=0, null=True, verbose_name='Points for draw'),
        ),
        migrations.AlterField(
            model_name='league',
            name='lost_points',
            field=models.IntegerField(choices=[(0, '0'), (1, '0.5'), (2, '1'), (3, '2'), (4, '3')], default=0, null=True, verbose_name='Points for loss'),
        ),
        migrations.AlterField(
            model_name='league',
            name='win_points',
            field=models.IntegerField(choices=[(0, '0'), (1, '0.5'), (2, '1'), (3, '2'), (4, '3')], default=0, null=True, verbose_name='Points for win'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.player', verbose_name='Black'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white', to='league.player', verbose_name='White'),
        ),
    ]
