# Generated by Django 3.1.3 on 2021-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_auto_20210207_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='nbs',
            field=models.FloatField(default=0, null=True, verbose_name='Neustadtl Sonneborn-Berger Score'),
        ),
    ]
