# Generated by Django 3.1.3 on 2021-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_standings_nbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='buchholz',
            field=models.FloatField(default=0, null=True, verbose_name='Buchholz Score'),
        ),
        migrations.AddField(
            model_name='standings',
            name='buchholzcut1',
            field=models.FloatField(default=0, null=True, verbose_name='Buchholz Cut 1 Score'),
        ),
        migrations.AddField(
            model_name='standings',
            name='matches1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Matches With Black'),
        ),
        migrations.AddField(
            model_name='standings',
            name='opprating',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Rating of Opponent less 1'),
        ),
        migrations.AddField(
            model_name='standings',
            name='win1',
            field=models.IntegerField(default=0, null=True, verbose_name='Won With Black'),
        ),
        migrations.AlterField(
            model_name='league',
            name='standings_order',
            field=models.IntegerField(choices=[(0, 'Points, Wins, Lost'), (1, 'Points, Tiebreak, Wins, Lost, Rating'), (2, 'Points, Score'), (3, 'FIDE Swiss Tiebreak System')], default=0, verbose_name='Standings order'),
        ),
    ]
