# Generated by Django 2.1.15 on 2021-10-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_auto_20210315_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'ordering': ('-points', '-win', '-matches', 'lost', '-rating', 'player__surename'), 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='black_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Black Rating'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='white_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='White Rating'),
        ),
    ]
