# Generated by Django 2.1.15 on 2021-11-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0032_auto_20211024_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Team Name')),
                ('league', models.CharField(max_length=200, null=True, verbose_name='League')),
                ('players', models.ManyToManyField(blank=True, related_name='team_players', to='league.Player', verbose_name='Players')),
            ],
        ),
        migrations.CreateModel(
            name='TeamFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('opponent', models.CharField(max_length=200, null=True, verbose_name='Opponent')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home', models.BooleanField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Fixture',
                'verbose_name_plural': 'Team Fixtures',
            },
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.IntegerField(choices=[(0, 'League'), (1, 'Swiss'), (2, 'Round Robin'), (3, 'Knockout')], default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='league.Player', verbose_name='Players'),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
    ]
