# Generated by Django 2.1.15 on 2021-12-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0033_auto_20211111_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='performance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Performance Rating'),
        ),
    ]
