# Generated by Django 2.1.15 on 2022-03-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0036_schedule_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='board',
            field=models.IntegerField(blank=True, null=True, verbose_name='Board'),
        ),
        migrations.AddField(
            model_name='pgn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pgn', to='league.Schedule', verbose_name='Game'),
        ),
    ]
