# Generated by Django 2.1.15 on 2022-03-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0037_auto_20220307_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='pgn',
        ),
        migrations.AlterField(
            model_name='pgn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgn', to='league.Schedule', verbose_name='Game'),
        ),
    ]
