# Generated by Django 2.1.15 on 2022-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0039_auto_20220415_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='winpercent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Win Percentage'),
        ),
        migrations.AlterField(
            model_name='league',
            name='standings_order',
            field=models.IntegerField(choices=[(0, 'Points, Wins, Lost'), (1, 'Points, Tiebreak, Wins, Lost, Rating'), (2, 'Points, Score'), (3, 'FIDE Swiss Tiebreak System'), (3, 'Win Percentage')], default=0, verbose_name='Standings order'),
        ),
    ]
