# Generated by Django 2.1.15 on 2022-08-09 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0043_auto_20220530_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(default=False)),
                ('played', models.IntegerField(blank=True, default=0, null=True)),
                ('won', models.IntegerField(blank=True, default=0, null=True)),
                ('draw', models.IntegerField(blank=True, default=0, null=True)),
                ('lost', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player', verbose_name='Team Player')),
            ],
            options={
                'verbose_name': 'Team Player',
                'verbose_name_plural': 'Team Players',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='listed_players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='league.Player', verbose_name='Team Captain'),
        ),
        migrations.AlterField(
            model_name='league',
            name='draw_points',
            field=models.IntegerField(choices=[(0, 0), (1, 0.5), (2, 1), (3, 2), (4, 3)], default=1, null=True, verbose_name='Points for draw'),
        ),
        migrations.AlterField(
            model_name='league',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='win_points',
            field=models.IntegerField(choices=[(0, 0), (1, 0.5), (2, 1), (3, 2), (4, 3)], default=2, null=True, verbose_name='Points for win'),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='Team'),
        ),
    ]
