# Generated by Django 2.1.15 on 2022-07-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0043_auto_20220530_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(default=False)),
                ('played', models.IntegerField(blank=True, default=0, null=True)),
                ('won', models.IntegerField(blank=True, default=0, null=True)),
                ('draw', models.IntegerField(blank=True, default=0, null=True)),
                ('lost', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Team Player',
                'verbose_name_plural': 'Team Players',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='league.Player', verbose_name='Captain'),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='Team'),
        ),
    ]
