# Generated by Django 2.1.15 on 2022-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0046_team_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='draw_points',
            field=models.IntegerField(choices=[(0, 0), (1, 0.5), (2, 1), (3, 2), (4, 3)], default=1, null=True, verbose_name='Points for draw'),
        ),
        migrations.AlterField(
            model_name='league',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='win_points',
            field=models.IntegerField(choices=[(0, 0), (1, 0.5), (2, 1), (3, 2), (4, 3)], default=2, null=True, verbose_name='Points for win'),
        ),
    ]
