# Generated by Django 2.1.15 on 2022-08-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0047_auto_20220725_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
