# Generated by Django 2.1.15 on 2022-08-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0048_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='player',
            name='chesscom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chess.com ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='player',
            name='fide',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='FIDE ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
    ]
