# Generated by Django 2.1.15 on 2023-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0051_auto_20230319_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fide_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fide Rating'),
        ),
        migrations.AddField(
            model_name='player',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='ECF Rating'),
        ),
    ]
