# Generated by Django 2.1.15 on 2023-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0052_auto_20230521_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
