# Generated by Django 2.1.15 on 2023-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0053_auto_20230521_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='extra_players',
            field=models.ManyToManyField(blank=True, related_name='seasons_extras', to='league.Player', verbose_name='Extra Players'),
        ),
    ]
