# Generated by Django 2.1.15 on 2023-09-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0054_season_extra_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, choices=[(0, 'President'), (1, 'Secretary'), (2, 'Assistant Secretary'), (3, 'Tournament Secretary'), (4, 'Club Steward'), (5, 'Auditor'), (6, 'Treasurer'), (7, 'Club Captain'), (8, 'Publicity Officer'), (9, 'Promotions Officer'), (10, 'Other')], null=True, verbose_name='Committe Position')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Player', verbose_name='Committee Member')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season', verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
            },
        ),
    ]
