# Generated by Django 2.1.15 on 2023-10-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0056_auto_20231012_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ecf_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name for ECF'),
        ),
    ]
