# Generated by Django 2.1.15 on 2024-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0057_player_ecf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'President'), (1, 'Secretary'), (2, 'Assistant Secretary'), (3, 'Tournament Secretary'), (4, 'Club Steward'), (5, 'Auditor'), (6, 'Treasurer'), (7, 'Club Captain'), (8, 'Publicity Officer'), (9, 'Promotions Officer'), (10, 'Other'), (11, 'Publicity Agent'), (12, 'Officer Without Portfolio')], null=True, verbose_name='Committe Position'),
        ),
    ]
