# Generated by Django 2.1.15 on 2024-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0058_auto_20240810_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfixture',
            name='away_score',
            field=models.IntegerField(blank=True, choices=[(-1, 0), (0, 0), (1, 0.5), (2, 1), (3, 1.5), (4, 2), (5, 2.5), (6, 3), (7, 3.5), (8, 4), (9, 4.5), (10, 5), (11, 5.5), (12, 6), (13, 6.5), (14, 7), (15, 7.5), (16, 8), (17, 8.5), (18, 9), (19, 9.5), (20, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='teamfixture',
            name='home_score',
            field=models.IntegerField(blank=True, choices=[(-1, 0), (0, 0), (1, 0.5), (2, 1), (3, 1.5), (4, 2), (5, 2.5), (6, 3), (7, 3.5), (8, 4), (9, 4.5), (10, 5), (11, 5.5), (12, 6), (13, 6.5), (14, 7), (15, 7.5), (16, 8), (17, 8.5), (18, 9), (19, 9.5), (20, 10)], null=True),
        ),
    ]
