# Generated by Django 5.1.3 on 2025-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0061_auto_20241112_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSTeamFixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('home_team', models.CharField(max_length=200, null=True, verbose_name='Home Team')),
                ('away_team', models.CharField(max_length=200, null=True, verbose_name='Away Team')),
                ('organisation', models.CharField(max_length=200, null=True, verbose_name='Organisation')),
                ('status', models.CharField(max_length=5, null=True, verbose_name='status')),
                ('event', models.CharField(max_length=200, null=True, verbose_name='Event')),
                ('home_score', models.IntegerField(blank=True, choices=[(-1, 'P'), (0, 0), (1, 0.5), (2, 1), (3, 1.5), (4, 2), (5, 2.5), (6, 3), (7, 3.5), (8, 4), (9, 4.5), (10, 5), (11, 5.5), (12, 6), (13, 6.5), (14, 7), (15, 7.5), (16, 8), (17, 8.5), (18, 9), (19, 9.5), (20, 10)], null=True)),
                ('away_score', models.IntegerField(blank=True, choices=[(-1, 'P'), (0, 0), (1, 0.5), (2, 1), (3, 1.5), (4, 2), (5, 2.5), (6, 3), (7, 3.5), (8, 4), (9, 4.5), (10, 5), (11, 5.5), (12, 6), (13, 6.5), (14, 7), (15, 7.5), (16, 8), (17, 8.5), (18, 9), (19, 9.5), (20, 10)], null=True)),
            ],
            options={
                'verbose_name': 'LMS Team Fixture',
                'verbose_name_plural': 'LMS Team Fixtures',
            },
        ),
    ]
