# Generated by Django 3.0.6 on 2020-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Event', max_length=200)),
                ('date', models.DateTimeField()),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
