# Generated by Django 3.0.6 on 2020-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
