# Generated by Django 3.0.6 on 2020-06-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('fen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
