# Generated by Django 2.1.15 on 2021-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_puzzle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
