# Generated by Django 2.1.15 on 2021-12-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
