# Generated by Django 2.1.15 on 2022-01-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20211217_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('publish', 'Can mark a news item as published')], 'verbose_name_plural': 'News'},
        ),
    ]
