# Generated by Django 2.1.15 on 2022-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='simul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Simul Entrants',
            },
        ),
    ]
