# Generated by Django 2.1.15 on 2022-08-16 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_simul'),
    ]

    operations = [
        migrations.AddField(
            model_name='simul',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
