# Generated by Django 2.1.15 on 2022-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_simul_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='htmlobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'HTML Object',
                'verbose_name_plural': 'HTML Objects',
            },
        ),
    ]
