# Generated by Django 2.1.15 on 2023-05-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_htmlobject_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdownitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Dropdown Item',
                'verbose_name_plural': 'Dropdown Items',
            },
        ),
        migrations.CreateModel(
            name='menuitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.AddField(
            model_name='htmlobject',
            name='type',
            field=models.IntegerField(choices=[(0, 'notification'), (1, 'about us')], default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dropdownitem',
            name='menuitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.menuitem', verbose_name='Menu Item'),
        ),
    ]
