# Generated by Django 2.1.15 on 2024-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlobject',
            name='body',
            field=models.TextField(max_length=100000),
        ),
    ]
