# Generated by Django 2.1.15 on 2024-08-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20240830_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlobject',
            name='body',
            field=models.TextField(max_length=1000000),
        ),
    ]
