# Generated by Django 2.1.15 on 2024-08-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20240831_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'verbose_name': 'Snippet', 'verbose_name_plural': 'Snippets'},
        ),
    ]
