# Generated by Django 2.1.15 on 2024-12-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20240831_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('publish_news', 'Can mark a news item as published')], 'verbose_name_plural': 'News'},
        ),
    ]
